language: python

python:
  - 2.7

install:
  - sudo apt-get update -qq
  - sudo apt-get remove libzmq3
  - sudo apt-get install -qq cython libzmq-dev

script:
  - python setup.py test

branches:
  except:
    - legacy
