language: python
cache: pip

python:
  - 2.7

sudo: false

addons:
  apt:
    packages:
    - libzmq3-dev

install:
  - pip install -r req.txt

script:
  - python setup.py test

branches:
  except:
    - legacy
